### ISSUE TITLE
Remove misp-module branch

### ISSUE THREAD

**Issue by ostefano** [davidonzo/apiosintDS#3] opened 2023-09-12 09:15 UTC
I see that the `misp-module` branch is used to unpin the `validators` dependency.
My understanding is because we want to make it compatible with the list of dependencies used by `misp-module` (https://github.com/MISP/misp-modules/blob/main/REQUIREMENTS).

It turns out `validators` is used only by `apiosintDS` so it should be safe to:
* pin the version inside `misp-module`
* remove the `misp-module` branch from `apiosintDS`

**Comment by ostefano** [comment] 2023-12-28 22:48
CC @davidonzo

**Comment by davidonzo** [comment] 2024-05-28 17:41
Sorry for the very long dalay in the answer...
Anyway, this should fix the issue => https://github.com/MISP/misp-modules/pull/666

Once the PR will be merged the misp-module branch become useless. But of course, I'll wait the PR merge before delete the branch.

Thanks.
Regards

**Comment by davidonzo** [comment] 2024-05-29 06:26
PR merged. The issue is resolved.

**Closed as completed by davidonzo** 2024-05-29 06:26 UTC
